### PR TITLE
Tomato

### PR DESCRIPTION
**Pull request by shereeramsey**
added tomatoes to the burger

### CODE REVIEW

**Comment by A1den159** [comment]
Hey sheree your branch is conflicting with the base branch

**Comment by shereeramsey** [comment]
Okay, I will resolve any conflicts

**Comment by shereeramsey** [comment]
Okay I have resolved the conflicts by moving Cheese to line 4 and keeping tomato at line 3 is this all good?

**Comment by A1den159** [comment]
Yeah thats fine thank you ill merge them now.

**Pull request merged**
